# Generated by Django 4.2.7 on 2024-01-28 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_organisation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'HR'), (2, 'Manager')]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
