# Generated by Django 4.2.7 on 2024-01-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_managers_account_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountSubmodel',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
