# Generated by Django 4.2.7 on 2024-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userorganisationmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
