# Generated by Django 4.2.7 on 2024-01-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumecomment',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.resume'),
        ),
        migrations.AddField(
            model_name='request',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.resume'),
        ),
        migrations.AddField(
            model_name='request',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancy'),
        ),
        migrations.AddField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.department'),
        ),
        migrations.AddField(
            model_name='manager',
            name='parent_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.manager'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldchoiceoptions',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancyrequestformfield'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.department'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.resume'),
        ),
    ]
