# Generated by Django 4.2.7 on 2023-11-11 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.vacancycategory'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumefile',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.resume'),
        ),
        migrations.AddField(
            model_name='resumecomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumecomment',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.resume'),
        ),
        migrations.AddField(
            model_name='request',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancy'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.organisationcategory'),
        ),
        migrations.AddField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.organisation'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.department'),
        ),
        migrations.AddField(
            model_name='criteriaform',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.organisation'),
        ),
        migrations.AddField(
            model_name='criteriafield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.criteriaform'),
        ),
        migrations.AddField(
            model_name='criteriachoices',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.criteriafield'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.resume'),
        ),
    ]
