# Generated by Django 4.2.7 on 2023-11-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_vacancy_owner_alter_vacancyrequest_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaChoiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=55)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyRequestChoiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=55)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='criteriafield',
            name='field_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='criteriafield',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'Short'), (2, 'Long'), (3, 'Select'), (4, 'Multiselect'), (5, 'Date')]),
        ),
        migrations.AlterField(
            model_name='vacancyrequestfield',
            name='field_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='vacancyrequestfield',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'Short'), (2, 'Long'), (3, 'Select'), (4, 'Multiselect'), (5, 'Date')]),
        ),
        migrations.DeleteModel(
            name='CriteriaChoices',
        ),
        migrations.AddField(
            model_name='vacancyrequestchoiceoptions',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancyrequestfield'),
        ),
        migrations.AddField(
            model_name='criteriachoiceoptions',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.criteriafield'),
        ),
    ]
