# Generated by Django 4.2.7 on 2023-12-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_criteriachoiceoptions_vacancyrequestchoiceoptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FormChoiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.SmallIntegerField(choices=[(1, 'Short'), (2, 'Long'), (3, 'Select'), (4, 'Multiselect'), (5, 'Date')])),
                ('field_name', models.CharField(max_length=55)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.form')),
            ],
        ),
        migrations.RemoveField(
            model_name='criteriafield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='criteriaform',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='vacancyrequest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vacancyrequestchoiceoptions',
            name='field',
        ),
        migrations.RemoveField(
            model_name='vacancyrequestfield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='vacancyrequestform',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='CriteriaChoiceOptions',
        ),
        migrations.DeleteModel(
            name='CriteriaField',
        ),
        migrations.DeleteModel(
            name='CriteriaForm',
        ),
        migrations.DeleteModel(
            name='VacancyRequest',
        ),
        migrations.DeleteModel(
            name='VacancyRequestChoiceOptions',
        ),
        migrations.DeleteModel(
            name='VacancyRequestField',
        ),
        migrations.DeleteModel(
            name='VacancyRequestForm',
        ),
    ]
