# Generated by Django 4.2.7 on 2024-01-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_member_organisation_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.AddField(
            model_name='manager',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.member'),
        ),
        migrations.AlterField(
            model_name='vacancyrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.member'),
        ),
        migrations.AlterField(
            model_name='vacancyrequeststatus',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Declined')], default=1),
        ),
    ]
