# Generated by Django 4.2.7 on 2024-02-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_manager_user_manager_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyrequest',
            name='data',
        ),
        migrations.AddField(
            model_name='resumecomment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.resumecomment'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='private_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='public_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='public_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.vacancyrequest'),
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='private_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='public_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vacancyrequestformfield',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.member'),
        ),
    ]
