# Generated by Django 4.2.7 on 2023-12-30 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_organisation_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.organisationcategory'),
        ),
    ]
