# Generated by Django 4.2.7 on 2024-01-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_department_parent_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.organisation'),
        ),
    ]
