# Generated by Django 4.2.7 on 2024-03-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_requeststatus_requeststatusresponders_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.interview')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.member')),
            ],
        ),
        migrations.RemoveField(
            model_name='requeststatusresponders',
            name='request_status',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Filtration'), (2, 'Pending'), (3, 'Approved'), (4, 'Declined')]),
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
        migrations.DeleteModel(
            name='RequestStatusResponders',
        ),
        migrations.AddField(
            model_name='interview',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.request'),
        ),
    ]
