# Generated by Django 4.2.7 on 2024-04-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_interview_interviewcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrequest',
            name='ceo_approve',
            field=models.BooleanField(default=False),
        ),
    ]
