# Generated by Django 4.2.7 on 2024-01-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_vacancy_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='candidate',
        ),
        migrations.AddField(
            model_name='resume',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='middle_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
