# Generated by Django 4.2.7 on 2024-01-21 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_remove_resume_candidate_resume_age_resume_email_and_more'),
        ('users', '0004_remove_candidate_accountsubmodel_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.vacancy'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=64)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.department')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.organisation')),
                ('parent_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.manager')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.manager'),
        ),
    ]
