# Generated by Django 4.2.7 on 2024-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_vacancyrequest_ceo_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyrequest',
            name='ceo_approve',
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='ceo_approved',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Declined')], default=1),
        ),
    ]
