# Generated by Django 4.2.7 on 2024-01-23 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_resume_vacancy_manager_alter_vacancy_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldChoiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('limir', models.IntegerField(null=True)),
                ('data', models.JSONField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.manager.Manager, to='crm.manager')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyRequestFormBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancyrequestform')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyRequestFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.SmallIntegerField(choices=[(1, 'Short'), (2, 'Long'), (3, 'Select'), (4, 'Multiselect'), (5, 'Date'), (6, 'Number'), (7, 'List')])),
                ('field_name', models.CharField(max_length=55)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.vacancyrequestformblock')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancyrequestform')),
            ],
        ),
        migrations.DeleteModel(
            name='FormChoiceOptions',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_title',
            field=models.CharField(default="Job title", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancycategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.AddField(
            model_name='fieldchoiceoptions',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancyrequestformfield'),
        )
    ]
