# Generated by Django 4.2.7 on 2024-05-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_remove_vacancy_limit_vacancyrequestform_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='full_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='VacancyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.member')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.vacancycomment')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vacancy')),
            ],
        ),
    ]
