# Generated by Django 4.2.7 on 2024-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_fieldchoiceoptions_vacancyrequest_vacancyrequestform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchoiceoptions',
            name='option',
            field=models.CharField(max_length=128),
        ),
    ]
