# Generated by Django 4.2.7 on 2024-01-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_fieldchoiceoptions_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyrequest',
            old_name='limir',
            new_name='limit',
        ),
        migrations.AlterField(
            model_name='fieldchoiceoptions',
            name='option',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
