# Generated by Django 4.2.7 on 2024-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_resume_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(null=True, upload_to='resume-images/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(default='bob', max_length=128),
            preserve_default=False,
        ),
    ]
