# Generated by Django 4.2.7 on 2024-07-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_resume_photo_alter_resume_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=55)),
                ('text', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.resume')),
            ],
        ),
    ]
