# Generated by Django 4.2.7 on 2024-07-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_resumeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='request',
        ),
        migrations.AddField(
            model_name='interview',
            name='resume',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm.resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Filtration'), (2, 'Pending'), (3, 'Approved'), (4, 'Declined')], default=1),
        ),
        migrations.AddField(
            model_name='resume',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.vacancy'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
