# Generated by Django 4.2.7 on 2024-07-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_interview_request_interview_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='name',
            field=models.CharField(default='Bob', max_length=72),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
