# Generated by Django 4.2.7 on 2024-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_interview_end_time_interview_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
